### ISSUE TITLE
Fonctions manquantes pour les `t_array`

### ISSUE THREAD

**Issue by tmielcza** [itheof/lib42#18]
`is_empty`
`get_last`

D'autres ?

**Comment by Kerollmops** [comment]
On attend ta PR

**Comment by tmielcza** [comment]
Si vous avez d'autres idées, que ce soit torché en une seule PR, d'un coup, et pas après 25 commits de modifs.

**Comment by theof** [comment]
Des macros seraient plus adaptees IMO.

**Comment by dariuskramer** [comment]
`array_get_last` => https://github.com/itheof/lib42/pull/19

**Comment by dariuskramer** [comment]
`is_empty` => https://github.com/itheof/lib42/pull/20

**Comment by dariuskramer** [comment]
`get_first` => https://github.com/itheof/lib42/commit/74bb6bf2e1945350975cd01a6d8816d456051e59

**Comment by dariuskramer** [comment]
Cloture de la PR, tout ce qui a été demandé est implémenter. On pourra toujours réouvrir si besoin.
