### ISSUE TITLE
Probleme d'affichage du ft_printf avec des nombres negatifs

### ISSUE THREAD

**Issue by tmielcza** [itheof/lib42#36]
Le printf deconne avec %d et les nombres negatifs: le moins (`-`) est mis en debut de ligne et ecrase l'eventuel caractere qui aurait du s'y trouver.

Exemple:
```c
ft_printf("coucou %s\n", -1);
```
donne comme output:
`-oucou 1`

**Comment by dariuskramer** [comment]
Fix: 41e03a3604b0caecf0d5bcb6f8bbe4d57bc4605f
